export class Persona {
    id: number = null;
    nombres: string = null;
    apellidos: string = null;
    documento: string = null;
    fecha_nacimiento: any = null;
    sexo: string = null;
    estado_civil: string = null;
    nacionalidad: string = null;
    ciudad_residencia: string = null;
    email: string = null;
    cel_1: string = null;
    cel_2: string = null;
    telefono: string = null;
    foto_perfil: string = null;
    familiares: any = null;
    ha_trabajado: any = null;
    redes_sociales: string = null;
    fecha_creacion: any = null;
    fecha_modificacion: any = null;
    usuario: any = null;
}